import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Profile } from "./profiles.js";

export type SdkTarget =
  | "android"
  | "swift"
  | "reactjs"
  | "reactnative"
  | "wordpress";

interface GeneratedFile {
  path: string;
  content: string;
  description: string;
}

function generateEnvFile(profile: Profile): GeneratedFile {
  const content = [
    `# Ethora SDK Configuration`,
    `# Profile: ${profile.name} (${profile.type})`,
    `# Generated by @ethora/setup`,
    ``,
    `ETHORA_APP_ID=${profile.appId}`,
    `ETHORA_APP_TOKEN=${profile.appToken}`,
    `ETHORA_APP_SECRET=${profile.appSecret}`,
    `ETHORA_APP_DOMAIN_NAME=${profile.domainName || ""}`,
    `ETHORA_API_BASE_URL=${profile.endpoints.apiUrl}`,
    `ETHORA_XMPP_HOST=${profile.endpoints.xmppHost}`,
    `ETHORA_XMPP_WS=${profile.endpoints.xmppWebSocket}`,
    `ETHORA_XMPP_BOSH=${profile.endpoints.xmppBosh}`,
    `ETHORA_XMPP_CONFERENCE=${profile.endpoints.xmppConference}`,
    profile.webAppUrl ? `ETHORA_WEB_APP_URL=${profile.webAppUrl}` : "",
    ``,
  ]
    .filter(Boolean)
    .join("\n");

  return { path: ".env.ethora", content, description: ".env.ethora" };
}

function generateAndroidConfig(profile: Profile): GeneratedFile[] {
  const gradleProps = [
    `# Ethora SDK Configuration`,
    `# Profile: ${profile.name} (${profile.type})`,
    `# Generated by @ethora/setup`,
    ``,
    `ethora.appId=${profile.appId}`,
    `ethora.appToken=${profile.appToken}`,
    `ethora.appSecret=${profile.appSecret}`,
    `ethora.domainName=${profile.domainName || ""}`,
    `ethora.baseUrl=${profile.endpoints.apiUrl}`,
    `ethora.xmppWebSocket=${profile.endpoints.xmppWebSocket}`,
    `ethora.xmppBosh=${profile.endpoints.xmppBosh}`,
    `ethora.xmppHost=${profile.endpoints.xmppHost}`,
    `ethora.xmppConference=${profile.endpoints.xmppConference}`,
    ``,
  ].join("\n");

  const kotlinConfig = [
    `package com.ethora.config`,
    ``,
    `// Generated by @ethora/setup — profile: ${profile.name}`,
    `object EthoraConfig {`,
    `    const val APP_ID = "${profile.appId}"`,
    `    const val APP_TOKEN = "${profile.appToken}"`,
    `    const val APP_SECRET = "${profile.appSecret}"`,
    `    const val DOMAIN_NAME = "${profile.domainName || ""}"`,
    `    const val BASE_URL = "${profile.endpoints.apiUrl}"`,
    `    const val XMPP_WS = "${profile.endpoints.xmppWebSocket}"`,
    `    const val XMPP_BOSH = "${profile.endpoints.xmppBosh}"`,
    `    const val XMPP_HOST = "${profile.endpoints.xmppHost}"`,
    `    const val XMPP_CONFERENCE = "${profile.endpoints.xmppConference}"`,
    `}`,
    ``,
  ].join("\n");

  return [
    {
      path: "ethora.properties",
      content: gradleProps,
      description: "ethora.properties (Gradle)",
    },
    {
      path: join("app", "src", "main", "java", "com", "ethora", "config", "EthoraConfig.kt"),
      content: kotlinConfig,
      description: "EthoraConfig.kt (Kotlin)",
    },
  ];
}

function generateSwiftConfig(profile: Profile): GeneratedFile {
  const content = [
    `import Foundation`,
    ``,
    `// Generated by @ethora/setup — profile: ${profile.name}`,
    `struct EthoraConfig {`,
    `    static let appId = "${profile.appId}"`,
    `    static let appToken = "${profile.appToken}"`,
    `    static let appSecret = "${profile.appSecret}"`,
    `    static let domainName = "${profile.domainName || ""}"`,
    `    static let baseUrl = "${profile.endpoints.apiUrl}"`,
    `    static let xmppWebSocket = "${profile.endpoints.xmppWebSocket}"`,
    `    static let xmppBosh = "${profile.endpoints.xmppBosh}"`,
    `    static let xmppHost = "${profile.endpoints.xmppHost}"`,
    `    static let xmppConference = "${profile.endpoints.xmppConference}"`,
    `}`,
    ``,
  ].join("\n");

  return { path: "EthoraConfig.swift", content, description: "EthoraConfig.swift" };
}

function generateWordPressConfig(profile: Profile): GeneratedFile {
  const content = [
    `<?php`,
    `// Ethora SDK Configuration`,
    `// Profile: ${profile.name} (${profile.type})`,
    `// Generated by @ethora/setup`,
    ``,
    `define('ETHORA_APP_ID', '${profile.appId}');`,
    `define('ETHORA_APP_TOKEN', '${profile.appToken}');`,
    `define('ETHORA_APP_SECRET', '${profile.appSecret}');`,
    `define('ETHORA_DOMAIN_NAME', '${profile.domainName || ""}');`,
    `define('ETHORA_API_BASE_URL', '${profile.endpoints.apiUrl}');`,
    `define('ETHORA_XMPP_HOST', '${profile.endpoints.xmppHost}');`,
    `define('ETHORA_XMPP_WS', '${profile.endpoints.xmppWebSocket}');`,
    `define('ETHORA_XMPP_BOSH', '${profile.endpoints.xmppBosh}');`,
    `define('ETHORA_XMPP_CONFERENCE', '${profile.endpoints.xmppConference}');`,
    ``,
  ].join("\n");

  return {
    path: "ethora-config.php",
    content,
    description: "ethora-config.php",
  };
}

export function generateConfig(
  profile: Profile,
  target: SdkTarget,
  outputDir: string
): string[] {
  let files: GeneratedFile[];

  switch (target) {
    case "android":
      files = generateAndroidConfig(profile);
      break;
    case "swift":
      files = [generateSwiftConfig(profile)];
      break;
    case "reactjs":
    case "reactnative":
      files = [generateEnvFile(profile)];
      break;
    case "wordpress":
      files = [generateWordPressConfig(profile)];
      break;
  }

  const written: string[] = [];
  for (const file of files) {
    const fullPath = join(outputDir, file.path);
    const dir = fullPath.substring(0, fullPath.lastIndexOf("/"));
    if (dir && !existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(fullPath, file.content);
    written.push(file.description);
  }

  return written;
}

export function showConfigPreview(profile: Profile, target: SdkTarget): string {
  const envFile = generateEnvFile(profile);
  switch (target) {
    case "android":
      return generateAndroidConfig(profile)[0].content;
    case "swift":
      return generateSwiftConfig(profile).content;
    case "wordpress":
      return generateWordPressConfig(profile).content;
    default:
      return envFile.content;
  }
}
