import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Profile, TestUser } from "./profiles.js";

export type SdkTarget =
  | "android"
  | "swift"
  | "reactjs"
  | "reactnative"
  | "wordpress";

interface GeneratedFile {
  path: string;
  content: string;
  description: string;
}

function generateEnvFile(profile: Profile): GeneratedFile {
  const content = [
    `# Ethora SDK Configuration`,
    `# Profile: ${profile.name} (${profile.type})`,
    `# Generated by @ethora/setup`,
    ``,
    `ETHORA_APP_ID=${profile.appId}`,
    `ETHORA_APP_TOKEN=${profile.appToken}`,
    `ETHORA_APP_SECRET=${profile.appSecret}`,
    `ETHORA_APP_DOMAIN_NAME=${profile.domainName || ""}`,
    `ETHORA_API_BASE_URL=${profile.endpoints.apiUrl}`,
    `ETHORA_XMPP_HOST=${profile.endpoints.xmppHost}`,
    `ETHORA_XMPP_WS=${profile.endpoints.xmppWebSocket}`,
    `ETHORA_XMPP_BOSH=${profile.endpoints.xmppBosh}`,
    `ETHORA_XMPP_CONFERENCE=${profile.endpoints.xmppConference}`,
    profile.webAppUrl ? `ETHORA_WEB_APP_URL=${profile.webAppUrl}` : "",
    ``,
  ]
    .filter(Boolean)
    .join("\n");

  return { path: ".env.ethora", content, description: ".env.ethora" };
}

/**
 * Detect if outputDir is a clone of ethora-sdk-android by checking for AppConfig.kt
 */
const APPCONFIG_PATH = join(
  "chat-core", "src", "main", "java", "com", "ethora", "chat", "core", "config", "AppConfig.kt"
);
const MAINACTIVITY_PATH = join(
  "chat-app", "src", "main", "java", "com", "ethora", "chat", "app", "MainActivity.kt"
);

function isAndroidSdk(outputDir: string): boolean {
  return existsSync(join(outputDir, APPCONFIG_PATH));
}

/**
 * Patch AppConfig.kt in-place with profile values.
 */
function patchAppConfig(outputDir: string, profile: Profile): string[] {
  const patched: string[] = [];
  const e = profile.endpoints;

  // Patch AppConfig.kt
  const appConfigFile = join(outputDir, APPCONFIG_PATH);
  if (existsSync(appConfigFile)) {
    let content = readFileSync(appConfigFile, "utf-8");

    // Replace default app token (long JWT on ?: fallback line)
    content = content.replace(
      /\?\s*"JWT eyJ[^"]+"/,
      `? "${profile.appToken}"`
    );

    // Replace default app ID
    content = content.replace(
      /const val defaultAppId: String = "[^"]+"/,
      `const val defaultAppId: String = "${profile.appId}"`
    );

    // Replace default base URL
    content = content.replace(
      /const val defaultBaseURL: String = "[^"]+"/,
      `const val defaultBaseURL: String = "${e.apiUrl}"`
    );

    // Replace default conference domain
    content = content.replace(
      /const val defaultConferenceDomain: String = "[^"]+"/,
      `const val defaultConferenceDomain: String = "${e.xmppConference}"`
    );

    // Replace XMPP settings
    content = content.replace(
      /devServer = "[^"]+"/,
      `devServer = "${e.xmppWebSocket}"`
    );
    content = content.replace(
      /host = "[^"]+"/,
      `host = "${e.xmppHost}"`
    );

    writeFileSync(appConfigFile, content);
    patched.push("AppConfig.kt (patched defaults)");
  }

  // Patch MainActivity.kt
  const mainActivityFile = join(outputDir, MAINACTIVITY_PATH);
  if (existsSync(mainActivityFile)) {
    let content = readFileSync(mainActivityFile, "utf-8");

    // Replace hardcoded baseUrl in login call and ChatConfig
    content = content.replace(
      /baseUrl = "https:\/\/api\.ethoradev\.com\/v1"/g,
      `baseUrl = "${e.apiUrl}"`
    );

    // Replace XMPP settings in ChatConfig
    content = content.replace(
      /devServer = "wss:\/\/xmpp\.ethoradev\.com:5443\/ws"/g,
      `devServer = "${e.xmppWebSocket}"`
    );
    content = content.replace(
      /host = "xmpp\.ethoradev\.com"/g,
      `host = "${e.xmppHost}"`
    );
    content = content.replace(
      /conference = "conference\.xmpp\.ethoradev\.com"/g,
      `conference = "${e.xmppConference}"`
    );

    // Replace hardcoded test credentials with test user (or clear if none)
    const testUser = profile.testUsers?.[0];
    content = content.replace(
      /mutableStateOf\("yukiraze9@gmail\.com"\)/,
      `mutableStateOf("${testUser?.email ?? ""}")`
    );
    content = content.replace(
      /mutableStateOf\("Qwerty123"\)/,
      `mutableStateOf("${testUser?.password ?? ""}")`
    );

    writeFileSync(mainActivityFile, content);
    patched.push("MainActivity.kt (patched endpoints + cleared test credentials)");
  }

  return patched;
}

function generateAndroidFallback(profile: Profile): GeneratedFile[] {
  const envFile = generateEnvFile(profile);
  return [
    { ...envFile, description: ".env.ethora (use with ETHORA_APP_TOKEN env var)" },
  ];
}

function generateSwiftConfig(profile: Profile): GeneratedFile {
  const content = [
    `import Foundation`,
    ``,
    `// Generated by @ethora/setup — profile: ${profile.name}`,
    `struct EthoraConfig {`,
    `    static let appId = "${profile.appId}"`,
    `    static let appToken = "${profile.appToken}"`,
    `    static let appSecret = "${profile.appSecret}"`,
    `    static let domainName = "${profile.domainName || ""}"`,
    `    static let baseUrl = "${profile.endpoints.apiUrl}"`,
    `    static let xmppWebSocket = "${profile.endpoints.xmppWebSocket}"`,
    `    static let xmppBosh = "${profile.endpoints.xmppBosh}"`,
    `    static let xmppHost = "${profile.endpoints.xmppHost}"`,
    `    static let xmppConference = "${profile.endpoints.xmppConference}"`,
    `}`,
    ``,
  ].join("\n");

  return { path: "EthoraConfig.swift", content, description: "EthoraConfig.swift" };
}

function generateWordPressConfig(profile: Profile): GeneratedFile {
  const content = [
    `<?php`,
    `// Ethora SDK Configuration`,
    `// Profile: ${profile.name} (${profile.type})`,
    `// Generated by @ethora/setup`,
    ``,
    `define('ETHORA_APP_ID', '${profile.appId}');`,
    `define('ETHORA_APP_TOKEN', '${profile.appToken}');`,
    `define('ETHORA_APP_SECRET', '${profile.appSecret}');`,
    `define('ETHORA_DOMAIN_NAME', '${profile.domainName || ""}');`,
    `define('ETHORA_API_BASE_URL', '${profile.endpoints.apiUrl}');`,
    `define('ETHORA_XMPP_HOST', '${profile.endpoints.xmppHost}');`,
    `define('ETHORA_XMPP_WS', '${profile.endpoints.xmppWebSocket}');`,
    `define('ETHORA_XMPP_BOSH', '${profile.endpoints.xmppBosh}');`,
    `define('ETHORA_XMPP_CONFERENCE', '${profile.endpoints.xmppConference}');`,
    ``,
  ].join("\n");

  return {
    path: "ethora-config.php",
    content,
    description: "ethora-config.php",
  };
}

export function generateConfig(
  profile: Profile,
  target: SdkTarget,
  outputDir: string
): string[] {
  // Android SDK: patch source files in-place when SDK structure detected
  if (target === "android" && isAndroidSdk(outputDir)) {
    return patchAppConfig(outputDir, profile);
  }

  let files: GeneratedFile[];

  switch (target) {
    case "android":
      files = generateAndroidFallback(profile);
      break;
    case "swift":
      files = [generateSwiftConfig(profile)];
      break;
    case "reactjs":
    case "reactnative":
      files = [generateEnvFile(profile)];
      break;
    case "wordpress":
      files = [generateWordPressConfig(profile)];
      break;
  }

  const written: string[] = [];
  for (const file of files) {
    const fullPath = join(outputDir, file.path);
    const dir = fullPath.substring(0, fullPath.lastIndexOf("/"));
    if (dir && !existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(fullPath, file.content);
    written.push(file.description);
  }

  return written;
}

export function showConfigPreview(profile: Profile, target: SdkTarget): string {
  const e = profile.endpoints;
  switch (target) {
    case "android":
      return [
        `// Will patch AppConfig.kt & MainActivity.kt with:`,
        `//   appId     = ${profile.appId}`,
        `//   baseUrl   = ${e.apiUrl}`,
        `//   xmppWs    = ${e.xmppWebSocket}`,
        `//   xmppHost  = ${e.xmppHost}`,
        `//   conference = ${e.xmppConference}`,
      ].join("\n");
    case "swift":
      return generateSwiftConfig(profile).content;
    case "wordpress":
      return generateWordPressConfig(profile).content;
    default:
      return generateEnvFile(profile).content;
  }
}
