import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import type { Profile, TestUser } from "./profiles.js";

export type SdkTarget =
  | "android"
  | "swift"
  | "reactjs"
  | "reactnative"
  | "wordpress";

interface GeneratedFile {
  path: string;
  content: string;
  description: string;
}

function generateEnvFile(profile: Profile): GeneratedFile {
  const content = [
    `# Ethora SDK Configuration`,
    `# Profile: ${profile.name} (${profile.type})`,
    `# Generated by @ethora/setup`,
    ``,
    `ETHORA_APP_ID=${profile.appId}`,
    `ETHORA_APP_TOKEN=${profile.appToken}`,
    `ETHORA_APP_SECRET=${profile.appSecret}`,
    `ETHORA_APP_DOMAIN_NAME=${profile.domainName || ""}`,
    `ETHORA_API_BASE_URL=${profile.endpoints.apiUrl}`,
    `ETHORA_XMPP_HOST=${profile.endpoints.xmppHost}`,
    `ETHORA_XMPP_WS=${profile.endpoints.xmppWebSocket}`,
    `ETHORA_XMPP_BOSH=${profile.endpoints.xmppBosh}`,
    `ETHORA_XMPP_CONFERENCE=${profile.endpoints.xmppConference}`,
    profile.webAppUrl ? `ETHORA_WEB_APP_URL=${profile.webAppUrl}` : "",
    ``,
    ...(profile.testUsers && profile.testUsers.length > 0
      ? [
          `# Test users (created by @ethora/setup)`,
          ...profile.testUsers.map(
            (u, i) =>
              `ETHORA_TEST_USER_${i + 1}_EMAIL=${u.email}\nETHORA_TEST_USER_${i + 1}_PASSWORD=${u.password}`
          ),
          ``,
        ]
      : []),
  ]
    .filter(Boolean)
    .join("\n");

  return { path: ".env.ethora", content, description: ".env.ethora" };
}

/**
 * Detect if outputDir is a clone of ethora-sample-android or ethora-sdk-android.
 */
const SAMPLE_BUILD_GRADLE = join("app", "build.gradle.kts");
const SAMPLE_ENV_FILE = ".env";
const APPCONFIG_PATH = join(
  "chat-core", "src", "main", "java", "com", "ethora", "chat", "core", "config", "AppConfig.kt"
);
const SWIFT_SAMPLE_PROJECT_YML = "project.yml";
const SWIFT_SAMPLE_SESSION_FILE = join("SDKPlayground", "PlaygroundSession.swift");

export function isAndroidSample(outputDir: string): boolean {
  return existsSync(join(outputDir, SAMPLE_BUILD_GRADLE));
}

export function isAndroidSdk(outputDir: string): boolean {
  return existsSync(join(outputDir, APPCONFIG_PATH));
}

/** ethora-sample-swift (standalone SDKPlayground app, XcodeGen-driven). */
export function isSwiftSample(outputDir: string): boolean {
  return existsSync(join(outputDir, SWIFT_SAMPLE_PROJECT_YML))
      && existsSync(join(outputDir, SWIFT_SAMPLE_SESSION_FILE));
}

/** ethora-sdk-swift (the SPM package root). */
export function isSwiftSdk(outputDir: string): boolean {
  return existsSync(join(outputDir, "Package.swift"));
}

/** Detect SDK project by target type */
export function isSdkProject(outputDir: string, target: SdkTarget): boolean {
  switch (target) {
    case "android":
      return isAndroidSample(outputDir) || isAndroidSdk(outputDir);
    case "swift":
      return isSwiftSample(outputDir) || isSwiftSdk(outputDir);
    case "reactjs":
      return existsSync(join(outputDir, "package.json")) && existsSync(join(outputDir, "config.ts"));
    case "reactnative":
      return existsSync(join(outputDir, "package.json")) && existsSync(join(outputDir, "app.json"));
    case "wordpress":
      return existsSync(join(outputDir, "ethora-assistant-plugin.php"));
  }
}

/**
 * Write `.env` at the ethora-sample-android repo root.
 *
 * The sample's `app/build.gradle.kts` reads this file at build time via its
 * own `loadEnvFile()` helper (which probes `.env` at the root, the app
 * module, etc.) and funnels values into `buildConfigField` entries such as
 * `ETHORA_APP_ID`, `ETHORA_USER_JWT`, `ETHORA_ROOM_JID`.
 *
 * We used to regex-patch the `buildConfigField("String", "KEY", "...")`
 * literals, but in the 26.04.21 sample refresh those values became Kotlin
 * string templates (`"\"${envOrDefault(...)}\""`) that the simple
 * `"[^"]*"` regex can't traverse — it stopped at the first embedded quote
 * and corrupted the file. Writing `.env` is the sample's own designed-for
 * injection point, so we use that instead.
 */
function patchSampleApp(outputDir: string, profile: Profile): string[] {
  const buildFile = join(outputDir, SAMPLE_BUILD_GRADLE);
  if (!existsSync(buildFile)) return [];

  const e = profile.endpoints;
  const testUser = profile.testUsers?.[0];

  const lines: string[] = [
    `# Generated by @ethora/setup — profile: ${profile.name}`,
    `# Consumed by app/build.gradle.kts loadEnvFile() at build time.`,
    `ETHORA_APP_ID=${profile.appId}`,
    `ETHORA_APP_TOKEN=${profile.appToken}`,
    `ETHORA_API_BASE_URL=${e.apiUrl}`,
    `ETHORA_XMPP_SERVER_URL=${e.xmppWebSocket}`,
    `ETHORA_XMPP_HOST=${e.xmppHost}`,
    `ETHORA_XMPP_CONFERENCE=${e.xmppConference}`,
  ];

  if (testUser) {
    // Email + password are always captured on test-user creation, so the
    // sample's Setup tab pre-fills email/password mode. That mode works
    // today (ethora-sample-android @ tf-dev).
    lines.push(`ETHORA_USER_EMAIL=${testUser.email}`);
    lines.push(`ETHORA_USER_PASSWORD=${testUser.password}`);
    // ETHORA_USER_JWT is intentionally NOT populated from testUser.jwt.
    // The Android SDK's JWTLoginConfig / the sample's "JWT" auth mode
    // targets the "client-flow" JWT — a JWT customers sign against their
    // Ethora app secret and submit to POST /users/client, verifying the
    // user via bring-your-own-auth. The token we capture via
    // EthoraAPI.loginUnderApp() is Ethora's own user-session token from
    // /v2/users/login-with-email — the server rejects it at /users/client
    // with `TOKEN_WRONG_TYPE (expected: client, actual: user)`. Leaving
    // ETHORA_USER_JWT blank makes the sample default to EMAIL_PASSWORD
    // mode instead of a mode that can't work with this token shape.
    //
    // A future enhancement could sign a real client-flow JWT here using
    // profile.appSecret (HMAC-SHA256 + user claims), which would unlock
    // automatic JWT-mode login. Out of scope until we confirm the claim
    // schema against the Ethora backend.
  }
  // ETHORA_ROOM_JID is intentionally not set — single-room mode is opt-in,
  // and a newly-created app has no rooms to pin to. Developers can add it
  // manually to this file when they want that flow.

  const envPath = join(outputDir, SAMPLE_ENV_FILE);
  writeFileSync(envPath, lines.join("\n") + "\n");

  const label = testUser
    ? `.env (endpoints + app token + ${testUser.username} credentials${testUser.jwt ? " + JWT" : ""})`
    : `.env (endpoints + app token)`;
  return [label];
}

/**
 * Patch AppConfig.kt in-place with profile values (legacy SDK repo).
 *
 * Used when the developer points setup at an `ethora-sdk-android` clone
 * directly (rather than the `ethora-sample-android` sample). Since the
 * sample was extracted on 26.04.21, the SDK repo no longer contains a
 * runnable `MainActivity.kt` — `AppConfig.kt` is the only file to patch.
 */
function patchAppConfig(outputDir: string, profile: Profile): string[] {
  const patched: string[] = [];
  const e = profile.endpoints;

  const appConfigFile = join(outputDir, APPCONFIG_PATH);
  if (!existsSync(appConfigFile)) return patched;

  let content = readFileSync(appConfigFile, "utf-8");

  // Replace default app token (long JWT on ?: fallback line)
  content = content.replace(
    /\?\s*"JWT eyJ[^"]+"/,
    `? "${profile.appToken}"`
  );

  // Replace default app ID
  content = content.replace(
    /const val defaultAppId: String = "[^"]+"/,
    `const val defaultAppId: String = "${profile.appId}"`
  );

  // Replace default base URL
  content = content.replace(
    /const val defaultBaseURL: String = "[^"]+"/,
    `const val defaultBaseURL: String = "${e.apiUrl}"`
  );

  // Replace default conference domain
  content = content.replace(
    /const val defaultConferenceDomain: String = "[^"]+"/,
    `const val defaultConferenceDomain: String = "${e.xmppConference}"`
  );

  // Replace XMPP settings
  content = content.replace(
    /devServer = "[^"]+"/,
    `devServer = "${e.xmppWebSocket}"`
  );
  content = content.replace(
    /host = "[^"]+"/,
    `host = "${e.xmppHost}"`
  );

  writeFileSync(appConfigFile, content);
  patched.push("AppConfig.kt (patched defaults)");

  return patched;
}

/**
 * Patch `ethora-sample-swift` (SDKPlayground) in-place with profile values.
 *
 * Injection strategy:
 * 1. Rewrite `@Published var <name>: String = "..."` defaults in
 *    `SDKPlayground/PlaygroundSession.swift` so that on first launch (empty
 *    `UserDefaults`) the form is pre-populated with the developer's app ID,
 *    endpoints, app token, and first test user's email / password / JWT.
 *    On subsequent launches the form loads from `UserDefaults` — if a
 *    developer already ran the playground once, they can hit "Reset" in the
 *    app or clear `sdk_playground_form_v1` in the simulator's prefs.
 * 2. Patch `project.yml`'s EthoraSDK `path: ../..` to a valid location.
 *    After the 26.04.22 extraction from `ethora-sdk-swift/Examples/`, the
 *    `../..` path no longer resolves to a `Package.swift`. If the setup
 *    tool cloned `ethora-sdk-swift` as a sibling directory (see
 *    `cloneSwiftSdkAlongside` in index.ts), we update the path to
 *    `../ethora-sdk-swift`. Otherwise we leave the yml untouched and the
 *    caller reports a warning with manual-fix instructions.
 */
function patchSwiftSample(outputDir: string, profile: Profile): string[] {
  const patched: string[] = [];
  const e = profile.endpoints;
  const testUser = profile.testUsers?.[0];

  const sessionFile = join(outputDir, SWIFT_SAMPLE_SESSION_FILE);
  if (existsSync(sessionFile)) {
    let content = readFileSync(sessionFile, "utf-8");

    const replacePublishedString = (name: string, value: string) => {
      const pattern = new RegExp(
        `(@Published var ${name}: String = )"[^"]*"`
      );
      content = content.replace(pattern, `$1"${value}"`);
    };

    replacePublishedString("baseURLString", e.apiUrl);
    replacePublishedString("appId", profile.appId);
    replacePublishedString("appToken", profile.appToken);
    replacePublishedString("xmppWebSocketURL", e.xmppWebSocket);
    replacePublishedString("xmppHost", e.xmppHost);
    replacePublishedString("xmppConference", e.xmppConference);

    if (testUser) {
      replacePublishedString("email", testUser.email);
      replacePublishedString("password", testUser.password);
      if (testUser.jwt) {
        replacePublishedString("jwtToken", testUser.jwt);
      }
    }

    writeFileSync(sessionFile, content);
    patched.push(
      testUser
        ? `SDKPlayground/PlaygroundSession.swift (endpoints + ${testUser.username} credentials${testUser.jwt ? " + JWT" : ""})`
        : `SDKPlayground/PlaygroundSession.swift (endpoints)`
    );
  }

  // If ethora-sdk-swift was cloned as a sibling, point project.yml at it.
  // `join("..", "ethora-sdk-swift")` — relative from the sample repo root.
  const siblingSdk = join(outputDir, "..", "ethora-sdk-swift");
  if (isSwiftSdk(siblingSdk)) {
    const ymlFile = join(outputDir, SWIFT_SAMPLE_PROJECT_YML);
    if (existsSync(ymlFile)) {
      let yml = readFileSync(ymlFile, "utf-8");
      const before = yml;
      yml = yml.replace(
        /^(\s*path:\s*)\.\.\/\.\.\s*$/m,
        "$1../ethora-sdk-swift"
      );
      if (yml !== before) {
        writeFileSync(ymlFile, yml);
        patched.push("project.yml (EthoraSDK path → ../ethora-sdk-swift)");
      }
    }
  }

  return patched;
}

function generateAndroidFallback(profile: Profile): GeneratedFile[] {
  const envFile = generateEnvFile(profile);
  return [
    { ...envFile, description: ".env.ethora (use with ETHORA_APP_TOKEN env var)" },
  ];
}

function generateSwiftConfig(profile: Profile): GeneratedFile {
  const content = [
    `import Foundation`,
    ``,
    `// Generated by @ethora/setup — profile: ${profile.name}`,
    `struct EthoraConfig {`,
    `    static let appId = "${profile.appId}"`,
    `    static let appToken = "${profile.appToken}"`,
    `    static let appSecret = "${profile.appSecret}"`,
    `    static let domainName = "${profile.domainName || ""}"`,
    `    static let baseUrl = "${profile.endpoints.apiUrl}"`,
    `    static let xmppWebSocket = "${profile.endpoints.xmppWebSocket}"`,
    `    static let xmppBosh = "${profile.endpoints.xmppBosh}"`,
    `    static let xmppHost = "${profile.endpoints.xmppHost}"`,
    `    static let xmppConference = "${profile.endpoints.xmppConference}"`,
    ...(profile.testUsers && profile.testUsers.length > 0
      ? [
          ``,
          `    // Test users (created by @ethora/setup)`,
          ...profile.testUsers.map(
            (u, i) =>
              `    static let testUser${i + 1}Email = "${u.email}"\n    static let testUser${i + 1}Password = "${u.password}"`
          ),
        ]
      : []),
    `}`,
    ``,
  ].join("\n");

  return { path: "EthoraConfig.swift", content, description: "EthoraConfig.swift" };
}

function generateWordPressConfig(profile: Profile): GeneratedFile {
  const content = [
    `<?php`,
    `// Ethora SDK Configuration`,
    `// Profile: ${profile.name} (${profile.type})`,
    `// Generated by @ethora/setup`,
    ``,
    `define('ETHORA_APP_ID', '${profile.appId}');`,
    `define('ETHORA_APP_TOKEN', '${profile.appToken}');`,
    `define('ETHORA_APP_SECRET', '${profile.appSecret}');`,
    `define('ETHORA_DOMAIN_NAME', '${profile.domainName || ""}');`,
    `define('ETHORA_API_BASE_URL', '${profile.endpoints.apiUrl}');`,
    `define('ETHORA_XMPP_HOST', '${profile.endpoints.xmppHost}');`,
    `define('ETHORA_XMPP_WS', '${profile.endpoints.xmppWebSocket}');`,
    `define('ETHORA_XMPP_BOSH', '${profile.endpoints.xmppBosh}');`,
    `define('ETHORA_XMPP_CONFERENCE', '${profile.endpoints.xmppConference}');`,
    ``,
  ].join("\n");

  return {
    path: "ethora-config.php",
    content,
    description: "ethora-config.php",
  };
}

/**
 * Write the React.js SDK's `.env.local` from profile values.
 *
 * The chat-component reads runtime endpoints from `import.meta.env` via
 * `src/utils/runtimeHostConfig.ts`, which Vite populates from the
 * `.env.local` file at the repo root. The legacy approach of patching
 * a tracked top-level `config.ts` was a no-op against runtime — that
 * file isn't on the runtime path any more — and committed customer
 * endpoints into source, which violates the product-code policy
 * (.claude/rules/product-code-policy.md in the BDSM workspace).
 *
 * Keys written here match what `runtimeHostConfig.buildRuntimeHostConfig`
 * reads. Pairs with ethora-chat-component PR #70 which wires
 * `src/App.tsx` defaults to those env vars.
 */
function patchReactConfig(outputDir: string, profile: Profile): string[] {
  const e = profile.endpoints;

  const lines = [
    `# Generated by @ethora/setup — profile: ${profile.name}`,
    `# Consumed by Vite at dev/build time; surfaces through src/config.ts.`,
    `# This file is gitignored — never commit real endpoints / app IDs.`,
    `VITE_APP_ID=${profile.appId}`,
    `VITE_API=${e.apiUrl}`,
    `VITE_DOMAIN_NAME=${profile.domainName || ""}`,
    `VITE_WEB_DOMAIN=${profile.webAppUrl ? profile.webAppUrl.replace(/^https?:\/\//, "").replace(/\/.*$/, "") : ""}`,
    `VITE_XMPP_HOST=${e.xmppHost}`,
    `VITE_XMPP_SERVICE=${e.xmppConference}`,
    `VITE_APP_XMPP_SERVICE=${e.xmppWebSocket}`,
    ``,
  ];

  const envPath = join(outputDir, ".env.local");
  writeFileSync(envPath, lines.join("\n"));
  return [".env.local (Vite env: VITE_API + VITE_APP_ID + VITE_XMPP_*)"];
}

export function generateConfig(
  profile: Profile,
  target: SdkTarget,
  outputDir: string
): string[] {
  // Android: patch sample app's build.gradle.kts or legacy SDK source files
  if (target === "android" && isAndroidSample(outputDir)) {
    return patchSampleApp(outputDir, profile);
  }
  if (target === "android" && isAndroidSdk(outputDir)) {
    return patchAppConfig(outputDir, profile);
  }

  // Swift: patch SDKPlayground (ethora-sample-swift) if detected; otherwise
  // fall through to the standalone EthoraConfig.swift generator below.
  if (target === "swift" && isSwiftSample(outputDir)) {
    return patchSwiftSample(outputDir, profile);
  }

  // React.js: patch config.ts if SDK detected
  if (target === "reactjs" && existsSync(join(outputDir, "config.ts"))) {
    return patchReactConfig(outputDir, profile);
  }

  let files: GeneratedFile[];

  switch (target) {
    case "android":
      files = generateAndroidFallback(profile);
      break;
    case "swift":
      files = [generateSwiftConfig(profile)];
      break;
    case "reactjs":
    case "reactnative":
      files = [generateEnvFile(profile)];
      break;
    case "wordpress":
      files = [generateWordPressConfig(profile)];
      break;
  }

  const written: string[] = [];
  for (const file of files) {
    const fullPath = join(outputDir, file.path);
    const dir = fullPath.substring(0, fullPath.lastIndexOf("/"));
    if (dir && !existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    writeFileSync(fullPath, file.content);
    written.push(file.description);
  }

  return written;
}

export function showConfigPreview(profile: Profile, target: SdkTarget): string {
  const e = profile.endpoints;
  switch (target) {
    case "android": {
      const testUser = profile.testUsers?.[0];
      const userLines = testUser
        ? [
            `//   ETHORA_USER_EMAIL     = ${testUser.email}`,
            `//   ETHORA_USER_PASSWORD  = ${testUser.password}`,
            testUser.jwt
              ? `//   ETHORA_USER_JWT       = <${testUser.username}'s JWT, ${testUser.jwt.length} chars>`
              : `//   ETHORA_USER_JWT       = (empty — sample will default to email/password login)`,
          ]
        : [`//   (no test user — Setup tab will open with blank email/password)`];
      return [
        `// Android sample (ethora-sample-android): will write .env at the repo root, consumed by app/build.gradle.kts at build time.`,
        `// Android SDK only (ethora-sdk-android): will patch AppConfig.kt defaults.`,
        `//   ETHORA_APP_ID         = ${profile.appId}`,
        `//   ETHORA_APP_TOKEN      = ${profile.appToken ? "<app JWT>" : "(empty)"}`,
        `//   ETHORA_API_BASE_URL   = ${e.apiUrl}`,
        `//   ETHORA_XMPP_SERVER_URL= ${e.xmppWebSocket}`,
        `//   ETHORA_XMPP_HOST      = ${e.xmppHost}`,
        `//   ETHORA_XMPP_CONFERENCE= ${e.xmppConference}`,
        ...userLines,
      ].join("\n");
    }
    case "reactjs": {
      const webDomain = profile.webAppUrl
        ? profile.webAppUrl.replace(/^https?:\/\//, "").replace(/\/.*$/, "")
        : "";
      return [
        `// React.js demo (ethora-chat-component): will write .env.local at the repo root, consumed by Vite.`,
        `//   VITE_APP_ID           = ${profile.appId}`,
        `//   VITE_API              = ${e.apiUrl}`,
        `//   VITE_DOMAIN_NAME      = ${profile.domainName || ""}`,
        `//   VITE_WEB_DOMAIN       = ${webDomain}`,
        `//   VITE_XMPP_HOST        = ${e.xmppHost}`,
        `//   VITE_XMPP_SERVICE     = ${e.xmppConference}`,
        `//   VITE_APP_XMPP_SERVICE = ${e.xmppWebSocket}`,
      ].join("\n");
    }
    case "swift": {
      const testUser = profile.testUsers?.[0];
      const userLine = testUser
        ? `//   email / password = ${testUser.email} / ${testUser.password}${testUser.jwt ? "  (+ JWT)" : ""}`
        : `//   (no test user — developer will fill email/password in the SDKPlayground Setup tab)`;
      return [
        `// Swift sample (ethora-sample-swift): will patch SDKPlayground/PlaygroundSession.swift @Published defaults so the Setup tab opens pre-filled with:`,
        `// Swift SDK only (ethora-sdk-swift): will write a standalone EthoraConfig.swift file instead.`,
        `//   baseURLString     = ${e.apiUrl}`,
        `//   appId             = ${profile.appId}`,
        `//   xmppWebSocketURL  = ${e.xmppWebSocket}`,
        `//   xmppHost          = ${e.xmppHost}`,
        `//   xmppConference    = ${e.xmppConference}`,
        userLine,
        `// If ethora-sdk-swift is cloned as a sibling, project.yml's EthoraSDK path will also be patched to resolve correctly.`,
      ].join("\n");
    }
    case "wordpress":
      return generateWordPressConfig(profile).content;
    default:
      return generateEnvFile(profile).content;
  }
}
